FROM ubuntu
RUN apt-get update &&\
apt-get install -y git qemu xorriso grub-efi wget zip unzip mtools\
&& wget https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip \
&& unzip i686-elf-tools-linux.zip -d /compilator &&\
mkdir shared &&\
git clone https://github.com/T0Mage/tpBootloaderlab	
 
